-- ============================================================
-- STEP 3: Run as nach_user to verify schema is correct
-- ============================================================

-- Check all tables
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;

-- Check all indexes
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE TABLE_NAME IN ('NACH_TRANSACTIONS','NACH_FILE_UPLOADS','NACH_REPROCESS_AUDIT','NACH_ERROR_CONFIG')
ORDER BY TABLE_NAME, INDEX_NAME;

-- Check all constraints
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('NACH_TRANSACTIONS','NACH_FILE_UPLOADS','NACH_REPROCESS_AUDIT','NACH_ERROR_CONFIG')
ORDER BY TABLE_NAME, CONSTRAINT_TYPE;

-- Check error config seeded
SELECT * FROM NACH_ERROR_CONFIG ORDER BY ERROR_CODE;

-- Check NACH_TRANSACTIONS structure
DESC NACH_TRANSACTIONS;
